apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: homework
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      # 1. Запросы пользователей и биллинга уходят в billing-service
      - path: /api/v1/users
        pathType: Prefix
        backend:
          service:
            name: billing-service
            port:
              number: 8000
      - path: /api/v1/billing
        pathType: Prefix
        backend:
          service:
            name: billing-service
            port:
              number: 8000

      # 2. Запросы создания заказов уходят в orders-service
      - path: /api/v1/orders
        pathType: Prefix
        backend:
          service:
            name: orders-service
            port:
              number: 8000

      # 3. Запросы получения писем уходят в notifications-service
      - path: /api/v1/notifications
        pathType: Prefix
        backend:
          service:
            name: notifications-service
            port:
              number: 8000
